name: 'week1'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the  week1 branch
  pull_request:
    types: [synchronize, opened, reopened, edited]
    branches:
      - 'week1_*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  week1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          working-directory: week1
          bundler-cache: true

      - name: Test Armstrong
        working-directory: week1
        run: ruby armstrong_test.rb
